volumes:
  data:

services:
  postgres:
    image: postgres:latest
    container_name: go-text-search-postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql